name: eriell
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.2
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.4.0
  vertical_percent_indicator: ^0.0.1
  google_fonts: ^4.0.4
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.68.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_onboarding_slider: ^1.0.11
  mask_text_input_formatter: ^2.8.0

flutter:

  uses-material-design: true

  assets:
    #    - assets/icons_svg/
    #    - assets/icons_png/
    - assets/icon/
    - assets/


  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/utils/fonts/Gilroy-Light.otf
        - asset: lib/utils/fonts/Gilroy-ExtraBold.otf
  #         - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700